name: Build RPM package

on:
  push:
    branches:
      - '*'
  workflow_dispatch: # Add manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone geary repository
      run: |
        git clone https://gitlab.gnome.org/GNOME/geary.git
        cd geary
        echo "LATEST_GEARY_VERSION=44.$(git rev-list --count HEAD)~$(git log -1 --format=%h)" >> $GITHUB_ENV
        echo "LATEST_GEARY_COMMIT=$(git log -1 --format=%h)" >> $GITHUB_ENV

    - name: Download information on previous build
      uses: actions/download-artifact@v2
      continue-on-error: true
      with:
        name: geary_build_latest_commit_id
        path: geary_build_latest_commit_id

    - name: Display structure of downloaded files
      run: ls -R

    - name: Check if source RPM file exists
      run: |
        if test "${{ env.LATEST_GEARY_COMMIT }}" == "$(cat geary_build_latest_commit_id)"; then
          echo "geary version $LAST_GEARY_COMMIT is already built. Skipping build."
          exit 0
        fi

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build SRPM package
      run: |
        cd $GITHUB_WORKSPACE && bash build.sh

    - name: Write commit id
      run: |
        echo "${{ env.LATEST_GEARY_COMMIT }}" > geary_build_commit_id

    - name: Upload SRPM package
      uses: actions/upload-artifact@v2
      with:
        name: geary_build_latest_commit_id
        path: geary_build_commit_id
