name: Build RPM package

on:
  push:
    branches:
      - '*'
  workflow_dispatch: # Add manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build SRPM package
      env:
        COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
        COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
      run: bash build.sh
